version: '3.7'
services:
  service1:
    image: yasirsatti/sofia-project-2_service1
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - service4
    
  service2:
    image: yasirsatti/sofia-project-2_service2
    build: ./service2
    ports:
    - target: 5000
      published: 5001
      protocol: tcp
      
  service3:
    image: yasirsatti/sofia-project-2_service3
    build: ./service3
    ports:
    - target: 5000
      published: 5002
      protocol: tcp
      
  service4:
    image: yasirsatti/sofia-project-2_service4
    build: ./service4
    ports:
    - target: 5000
      published: 5003
      protocol: tcp
    depends_on:
    - service2 
    - service3
  
   jenkins:
     image: jenkins/jenkins:latest
     environment:
       - JENKINS_OPTS="--prefix=/jenkins"
