import pytest
from application import routes

def test_generator():

    assert routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
    or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
        or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
            or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                    or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                        or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                            or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                    or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                        or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                            or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                    or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                        or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                            or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                    or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                        or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                            or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                                    or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                                        or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                                            or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                                                or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                                    or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                                                        or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                                                            or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                                                                or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                                                                    or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                                                        or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                                                                            or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                                                                                or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                                                                                    or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                                                                                        or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                                                                            or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                                                                                                or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                                                                                                    or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                                                                                                        or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                                                                                                            or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                                                                                                or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Red Dog") \
                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Red Elephant") \
                                                                                                                                                                        or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Red Bear") \
                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Red Cat") \
                                                                                                                                                                                or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Red House") \
                                                                                                                                                                                    or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                        or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                            or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                    or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                        or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                            or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                    or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                        or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                            or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                    or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                        or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                            or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                                    or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                                        or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                                            or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                                or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                                                    or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                                                        or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                                                            or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                                                or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                                                                    or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                                                                        or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                                                                            or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                                                                or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                                                                                    or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                                                                                        or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                                                                                            or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                                                                                or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") \
                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Yellow Tractor") \
                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Yellow Room") \
                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Yellow Horse") \
                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Yellow Disney Character") 
                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Pink Person") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Pink Train") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Pink Street") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Pink Car") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("1 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("1 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("1 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("2 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("3 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("4 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("5 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("6 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("7 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("8 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or routes.generator() == ("9 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Blue Food") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Blue Squid With Attitude") \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            or routes.generator() == ("10 shades only using the medium Watercolour Paint and your Subject is a Blue Sports Event") \


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                            